name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Kubernetes CLI
        uses: azure/setup-kubectl@v4

      - name: Authenticate with Kubernetes
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Build and Push Docker Image for Argus
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          cd argus/
          docker build -t ${{ secrets.DOCKER_IMAGE_TAG }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_IMAGE_TAG }}:${{ github.sha }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f .k3s/ --kubeconfig=kubeconfig.yaml
          kubectl set image deployment/${{ vars.K3S_DEPLOYMENT }} -n ${{ vars.K3S_NAMESPACE }} ${{ vars.K3S_DEPLOYMENT }}=${{ secrets.DOCKER_IMAGE_TAG }}:${{ github.sha }} --kubeconfig=kubeconfig.yaml
          kubectl rollout status deployment/${{ vars.K3S_DEPLOYMENT }} -n ${{ vars.K3S_NAMESPACE }} --kubeconfig=kubeconfig.yaml